# Generated by Django 4.2 on 2023-07-30 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_card_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
        ),
    ]
